---
kind: pipeline
type: docker
name: web

steps:
- name: npm install
  image: node:12.13.0-alpine
  commands:
  -  yarn install --registry=https://registry.npm.taobao.org

- name: build
  image: node:12.13.0-alpine
  commands:
  -  yarn build

# - name: rsync
#   image: drillster/drone-rsync
#   settings:
#     user: root
#     key:
#       from_secret: rsync_key
#     hosts:
#       - 59.110.227.202
#     source: ./dist/*
#     target: /root/vue_test
#     secrets: [ rsync_key ]