---
kind: pipeline
type: docker
name: web

steps:
- name: docker
  image: python:alpine3.14
  commands:
#   -  docker pull python:alpine3.14


- name: npm install
  image: node:12.0-alpine
  commands:
  -  yarn install --registry=https://registry.npm.taobao.org