---
kind: pipeline
type: docker
name: web

clone:
  disable: true

steps:
- name: clone
  pull: if-not-exists
  image: alpine/git
  volumes:
    - name: sshkeys
      path: /root/.ssh
  commands:
  -  echo $DRONE_GIT_SSH_URL
  -  git clone $DRONE_GIT_SSH_URL .

- name: npm install
  image: node:12.13.0-alpine
  commands:
  -  yarn install --registry=https://registry.npm.taobao.org

- name: build
  image: node:12.13.0-alpine
  commands:
  -  yarn build

- name: scp
  image: appleboy/drone-scp
  settings:
    host: 59.110.227.202
    username: root
    password: Qbwagx5liu
    port: 22
    target: /root/vue_test
    source: ./dist/*