---
kind: pipeline
type: docker
name: web

steps:
- name: docker
  image: python:alpine3.14
  commands:
  -  docker pull python:alpine3.14


- name: yarn
  image: node:alpine
  commands:
  -  npm install -g yarn

- name: npm install
  image: node:alpine
  commands:
  -  yarn install --registry=https://registry.npm.taobao.org